package com.gaurav.autosignalscanner
import android.app.*;import android.content.*;import android.os.*;import androidx.core.app.NotificationCompat;import kotlinx.coroutines.*;import okhttp3.*;import org.json.JSONObject;import java.text.SimpleDateFormat;import java.util.*
class ScannerService:Service(){
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.IO);private val client=OkHttpClient();private val pending=mutableListOf<P>();data class P(val pair:String,val dir:String,val entry:Double,val due:Long,val time:String)
 override fun onCreate(){super.onCreate();channel()}
 override fun onStartCommand(i:Intent?,f:Int,id:Int):Int{if(i?.action=="STOP"){scope.cancel();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();return START_NOT_STICKY};startForeground(1,n("Scanner चालू है","Health monitoring active"));scope.launch{loop()};return START_STICKY}
 private suspend fun loop(){while(scope.isActive){try{scan();verify()}catch(e:Exception){health("ERROR","—","Request failed: "+(e.message?:"network error"))};delay(15000)}}
 private fun get(url:String):JSONObject{val r=client.newCall(Request.Builder().url(url).build()).execute();val s=r.body?.string()?:"";val code=r.code;r.close();if(code !in 200..299)throw Exception("HTTP "+code);return JSONObject(s)}
 private fun scan(){val d=get("https://audusd-2-min-signal.hatchable.site/api/best-signal");val sig=d.optString("signal");val pair=d.optString("pair","—");val score=d.optInt("score");val gap=d.optInt("gap");val scanned=d.optJSONArray("scanned");val list=StringBuilder();if(scanned!=null)for(i in 0 until scanned.length()){val x=scanned.getJSONObject(i);if(i>0)list.append(", ");list.append(x.optString("pair")).append(" ").append(x.optInt("score"))};val reason=if(sig=="UP"||sig=="DOWN")"ACTIONABLE "+sig else "WAIT: score "+score+" (need 80), gap "+gap+" (need 40)";health("LIVE",pair+" "+score,""+reason+"\nScanned: "+list)
 if(sig!="UP"&&sig!="DOWN")return;val entry=d.optDouble("entryPrice",d.optDouble("entry",Double.NaN));if(entry.isNaN()){health("ERROR",pair+" "+score,"Signal had no entry price");return};val now=System.currentTimeMillis();val t=fmt(now);val key=pair+"-"+sig+"-"+(now/60000);val sp=getSharedPreferences("scanner",0);if(sp.getString("last","")==key)return;sp.edit().putString("last",key).apply();pending.add(P(pair,sig,entry,now+120000,t));notifyUser(100+pending.size,pair+" • "+sig+" • 2 MIN","Entry "+t+" • "+entry+" • score "+score)}
 private fun health(api:String,best:String,reason:String){getSharedPreferences("scanner",0).edit().putString("health","Last scan: "+fmt(System.currentTimeMillis())+"\nAPI: "+api+"\nBest: "+best+"\nReason: "+reason).apply()}
 private fun verify(){val now=System.currentTimeMillis();val it=pending.iterator();while(it.hasNext()){val p=it.next();if(now<p.due)continue;val d=get("https://audusd-2-min-signal.hatchable.site/api/result?pair="+java.net.URLEncoder.encode(p.pair,"UTF-8")+"&signal="+p.dir+"&entry="+p.entry);val res=d.optString("result","PENDING");if(res=="PENDING")continue;val exit=d.optDouble("exitPrice",Double.NaN);val sp=getSharedPreferences("scanner",0);if(res=="WIN")sp.edit().putInt("mwin",sp.getInt("mwin",0)+1).apply() else if(res=="LOSS")sp.edit().putInt("mloss",sp.getInt("mloss",0)+1).apply();sp.edit().putInt("opending",sp.getInt("opending",0)+1).apply();val line=p.time+" → "+fmt(now)+" • "+p.pair+" "+p.dir+"\nMarket "+p.entry+" → "+(if(exit.isNaN())"?" else exit)+" • "+res+"\nOlymptrade: awaiting verified feed";sp.edit().putString("history",line+"\n\n"+(sp.getString("history","")?:"")).apply();notifyUser(500+line.hashCode(),p.pair+" • "+p.dir+" • "+res,"2-minute market result");it.remove()}}
 private fun fmt(ms:Long)=SimpleDateFormat("hh:mm:ss a",Locale.getDefault()).format(Date(ms));private fun channel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("scan","Signal Scanner",NotificationManager.IMPORTANCE_HIGH))};private fun n(t:String,x:String)=NotificationCompat.Builder(this,"scan").setSmallIcon(android.R.drawable.ic_popup_reminder).setContentTitle(t).setContentText(x).setPriority(NotificationCompat.PRIORITY_HIGH).setOngoing(t.contains("चालू")).build();private fun notifyUser(id:Int,t:String,x:String)=getSystemService(NotificationManager::class.java).notify(id,n(t,x));override fun onBind(i:Intent?)=null
}